param([string]$AccessToken,[string]$ThumbMediaId)

# Read the HTML generated by wechat-article-formatter
$html=Get-Content "C:\Users\Administrator\.openclaw\workspace\mazda-skyactiv-article.html" -Raw -Encoding UTF8

# Remove DOCTYPE, html, head, body tags, keep only content
$html=$html -replace '(?s).*?<body[^>]*>',''
$html=$html -replace '(?s)</body>.*',''

# Remove H1 title comment
$html=$html -replace '<!--.*?-->'

# Escape for JSON
$html=$html -replace '\\','\\\\' -replace '"','\"'

# Build JSON
$json=@"
{"articles":[{"title":"14:1 鐨勯瓟娉曪細椹嚜杈惧浣曠敤鏈€绗ㄧ殑鍐呯噧鏈烘妧鏈紝鍦ㄧ數鍔ㄦ椂浠ｆ潃鍑轰竴鏉¤璺紵","author":"Nice 鍝?,"digest":"椹嚜杈惧垱椹拌摑澶╂妧鏈繁搴﹁В鏋?,"content":"$html","thumb_media_id":"$ThumbMediaId","need_open_comment":1,"only_fans_can_comment":0}]}
"@

$url="https://api.weixin.qq.com/cgi-bin/draft/add?access_token=$AccessToken"
Write-Host "Publishing with wechat-article-formatter tech theme..."
$response=Invoke-RestMethod -Uri $url -Method Post -Body $json -ContentType "application/json; charset=utf-8"
Write-Output "鉁?Published!"
Write-Output "Media ID: $($response.media_id)"
