param([string]$AccessToken,[string]$ThumbMediaId)

# Read HTML generated by wechat-article-formatter
$htmlPath="C:\Users\Administrator\.openclaw\workspace\mazda-skyactiv-article.html"
$html=Get-Content $htmlPath -Raw -Encoding UTF8

# Extract only body content (remove DOCTYPE, html, head, body tags)
$match=[regex]::Match($html,'<body[^>]*>(.*?)</body>')
if($match.Success){
    $content=$match.Groups[1].Value.Trim()
}else{
    $content=$html
}

# Remove HTML comments
$content=$content -replace '<!--.*?-->',''

# Write to temp file for verification
$content|Out-File "C:\Users\Administrator\.openclaw\workspace\content-extracted.html" -Encoding UTF8
Write-Host "Extracted content length: $($content.Length) chars"

# Escape for JSON
$content=$content -replace '\\','\\\\' -replace '"','\"'

# Build JSON
$json=@"
{"articles":[{"title":"14:1 鐨勯瓟娉曪細椹嚜杈惧浣曠敤鏈€绗ㄧ殑鍐呯噧鏈烘妧鏈紝鍦ㄧ數鍔ㄦ椂浠ｆ潃鍑轰竴鏉¤璺紵","author":"Nice 鍝?,"digest":"椹嚜杈惧垱椹拌摑澶╂妧鏈繁搴﹁В鏋?,"content":"$content","thumb_media_id":"$ThumbMediaId","need_open_comment":1,"only_fans_can_comment":0}]}
"@

# Publish
$url="https://api.weixin.qq.com/cgi-bin/draft/add?access_token=$AccessToken"
Write-Host "Publishing with wechat-article-formatter tech theme..."
try{
    $response=Invoke-RestMethod -Uri $url -Method Post -Body $json -ContentType "application/json; charset=utf-8"
    if($response.media_id){
        Write-Output "鉁?Published successfully!"
        Write-Output "Media ID: $($response.media_id)"
    }else{
        Write-Output "鉂?Failed: $($response.errmsg)"
    }
}catch{
    Write-Output "鉂?Error: $_"
}
